### ISSUE TITLE
when i use mint public sale i get Error: Public sale is currently closed

### ISSUE THREAD

**Issue by jokereven** [CoinbaseWallet/nft-minting-starter-kit#34]
1、it's my Contract address https://goerli.etherscan.io/address/0x42fa97571041c96167b3305cf7c89cd4b2af7158

## .env

# Goerli JSON RPC URL (Required for Goerli deployment)
GOERLI_API_URL=https://eth-goerli.g.alchemy.com/v2/RF8yubFYyclwm8b9SHxnd04CprKwQcRX

# Mainnet JSON RPC URL (Required for Mainnet deployment)
MAINNET_API_URL=https://eth-mainnet.g.alchemy.com/v2/eUk0BL63e_xBVKI9WNYKBKiy0ZlI4lzA

# Polygon JSON RPC URL (Optional)
POLYGON_API_URL=

# Private Key used to deploy NFT (Required)
PRIVATE_KEY=*******

# Public Key used to deploy NFT (Required)
PUBLIC_KEY=0x4aA717ef6C31fd152aa5C4d2601eC22C27Da2b78

# Wallet to receive NFT royalties (Required to deploy contract)
ROYALTY_RECEIVER_ADDR=0x4aA717ef6C31fd152aa5C4d2601eC22C27Da2b78

# Etherscan API Key to verify contract on Etherscan (Optional)
ETHERSCAN_API_KEY=*****

# Polygonscan API Key to verify contract on Polygonscan (Optional)
POLYGONSCAN_API_KEY=

# Token Base URI for NFT collection
BASE_URI=https://gateway.pinata.cloud/ipfs/QmXqVV2Dy8GVBx41LwuSuhxoVnzWHQJ7gZN5dDRYxeiu94
 # modify as needed

# For setting provenance hash (Optional)
PROVENANCE_HASH=

# Token Collection URI
COLLECTION_URI=https://gateway.pinata.cloud/ipfs/QmTYo65YBGZe1GCUPG1G4QcaRmVukRNypSUVcGQPLsjzsj # modify as needed

# NFT Contract Address (Fill after running deploy script, required for running tasks)
CONTRACT_ADDRESS=0x42Fa97571041C96167B3305CF7c89CD4B2af7158

2、Matedate https://gateway.pinata.cloud/ipfs/QmXqVV2Dy8GVBx41LwuSuhxoVnzWHQJ7gZN5dDRYxeiu94/

3、all thing do over and when i yarn dev coinbase of frontend, when i mint public sale i get Error: Public sale is currently closed

what should i do respect, peace.

**Comment by jawnjohn** [comment]
Did you try to set public sale active before minting? 
`yarn setPublicSaleActive`

**Comment by jokereven** [comment]
> Did you try to set public sale active before minting? `yarn setPublicSaleActive`

i try yarn setPublicSaleActive and then i get okay ,thank you peace。
